runtime: php
env: flex

runtime_config: 
  document_root: public

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:MPf432qr029OrrVeQchLvxLbjuM8xxL2lJsgFAvrrag=
    APP_NAME: "RECYCLEAR"

    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: 34.101.230.24
    DB_PORT: 3306
    DB_DATABASE: recyclear
    DB_USERNAME: recyclear-admin
    DB_PASSWORD: recyclear-admin